# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/nanoc
image: ruby:2.3

cache:
  key: "ruby-231"
  paths:
  - vendor/ruby

pages:
  stage: deploy
  environment:
    name: production
  script:
  - bundle install
  - rake pull_repos
  - nanoc
  artifacts:
    paths:
    - public
  only:
  - master
