# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/nanoc
image: ruby:2.3

pages:
  script:
  - bundle install
  - nanoc
  artifacts:
    paths:
    - public
  only:
  - master
