# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/nanoc
image: ruby:2.3

cache:
  key: "ruby-231"
  paths:
  - vendor/ruby

stages:
  - test
  - deploy

before_script:
  - bundle install --jobs 4 --path vendor

verify_compile:
  stage: test
  script:
    - rake pull_repos
    - nanoc
  except:
    - master

scss_lint:
  stage: test
  script:
    - bundle exec scss-lint

pages:
  stage: deploy
  environment:
    name: production
  script:
    - rake pull_repos
    - nanoc
  artifacts:
    paths:
    - public
  only:
  - master
