# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/nanoc
image: ruby:2.3

cache:
  key: "ruby-231"
  paths:
  - vendor/ruby

stages:
  - test
  - deploy

before_script:
  - bundle install --jobs 4 --path vendor

verify_compile:
  stage: test
  script:
    - rake pull_repos
    - nanoc
  artifacts:
    paths:
      - public
    expire_in: 1h
  except:
    - master

scss_lint:
  stage: test
  script:
    - bundle exec scss-lint

review:
  stage: deploy
  variables:
    APPS_DOMAIN: "178.62.207.141.xip.io"
  script:
    - rsync -av --delete public /srv/nginx/pages/$CI_BUILD_REF_NAME
  environment:
    name: review/$CI_BUILD_REF_NAME
    url: http://$CI_BUILD_REF_NAME.$APPS_DOMAIN
    on_stop: review_stop
  only:
    - branches
  except:
    - master
  tags:
    - nginx
    - review-apps

review_stop:
  stage: deploy
  script:
    - rm -rf public /srv/nginx/pages/$CI_BUILD_REF_NAME
  when: manual
  environment:
    name: review/$CI_BUILD_REF_NAME
    action: stop
  tags:
    - nginx
    - review-apps

pages:
  stage: deploy
  environment:
    name: production
  script:
    - rake pull_repos
    - nanoc
  artifacts:
    paths:
    - public
  only:
  - master
