# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/nanoc
image: ruby:2.3

cache:
  key: "ruby-231"
  paths:
  - vendor/ruby

verify_compile:
  script:
    - bundle install --path vendor
    - rake pull_repos
    - nanoc
  except:
    - master

pages:
  stage: deploy
  environment:
    name: production
  script:
  - bundle install --path vendor
  - rake pull_repos
  - nanoc
  artifacts:
    paths:
    - public
  only:
  - master
